# vim:ft=ansible:

- src: https://github.com/geerlingguy/ansible-role-jenkins.git
  version: 1.2.3
  name: geerlingguy.jenkins
- src: https://github.com/jdauphant/ansible-role-nginx.git
  version: v1.3.4
  name: jdauphant.nginx
- src: https://github.com/alphagov/ansible-role-openconnect.git
  version: "0.1"
  name: openconnect
- src: https://github.com/rvm/rvm1-ansible.git
  version: v1.3.7
  name: rvm_io.rvm1-ruby
