# vim:ft=ansible:
---
# Bring up jenkins ci master server.
- hosts: all
  sudo: yes
  roles:
    - geerlingguy.jenkins
    - jdauphant.nginx
  pre_tasks:
    - name: install snake oil ssl certificates
      apt: name=ssl-cert state=present
  vars:
    jenkins_plugins:
      - git
      - ssh
      - job-dsl
    nginx_sites:
      ssl_reverse_proxy:
        - listen 443 ssl
        - ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem
        - ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key
        - server_name jenkins.tooling.paas.alphagov.co.uk
        - location / {
          proxy_pass http://localhost:8080;
          proxy_redirect default;
          proxy_redirect http://$host/ https://$host/;
          proxy_redirect http://$hostname/ https://$host/;
          proxy_read_timeout 15s;
          proxy_connect_timeout 15s;
          }
      default:
        - listen 80
        - return 301 https://$host$request_uri
    nginx_configs:
      proxy:
        - proxy_set_header Host $http_host
        - proxy_set_header X-Real-IP  $remote_addr
        - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
        - proxy_set_header X-Forwarded-Proto https
  tasks:
    - name: install required packages
      action: apt pkg={{item}} state=installed
      with_items:
        - git
        - unzip
        - python-pip
    - name: ensure necessary package for uri checking is available
      pip: name=httplib2
    - name: download terraform
      get_url: url=https://dl.bintray.com/mitchellh/terraform/terraform_0.4.2_linux_amd64.zip dest=/tmp/terraform.zip mode=0440
      notify:
        - unzip terraform.zip to /usr/local/bin
    - name: copy default dsl seed config.xml to jenkins master
      copy: src=dsl/config.xml dest=/tmp/config.xml owner=jenkins group=jenkins mode=0644
    - name: create default dsl seed job
      shell: "curl -X POST 'http://127.0.0.1:8080/createItem?name=default-dsl-job' --data-binary '@config.xml' -H 'Content-Type: text/xml'"
      args:
        chdir: /tmp/
    - name: create jenkins seed job directory structure
      copy: src=jobs dest=/var/lib/jenkins/jobs/default-dsl-job/workspace directory_mode=0750 mode=0640 owner=jenkins group=jenkins
    - name: generate jenkins job from dsl seed job
      uri: url='http://127.0.0.1:8080/job/default-dsl-job/build'
        method=POST 
        status_code=201
  handlers:
    - name: unzip terraform.zip to /usr/local/bin 
      unarchive: src=/tmp/terraform.zip dest=/usr/local/bin copy=no


