---
ami_id: "ami-47a23a30"

demo_environment_name: "demo"
reference_name: "master"

ssh_key_name: multicloud-deploy
ec2_access_key: lookup('env', 'AWS_ACCESS_KEY_ID')
ec2_secret_key: lookup('env', 'AWS_SECRET_ACCESS_KEY')

java_home: "/usr/lib/jvm/java-7-openjdk-amd64/jre"
keystore_password: "changeit"

github_web_uri: "https://github.com"
github_api_uri: "https://api.github.com/api/v3"
github_hostname: "github.com"
client_id: "github_app_client_id"
client_secret: "github_app_client_secret"

jenkins_mail_name: "Jenkins CI"
jenkins_mail: "itsme@jenkins.com"
smtp_server: "aspmx.l.google.com"

gpg_public_key_id: F35E9C9E

terraform_version: "0.6.3"

permissions:
  admins:
    - hudson.scm.SCM.Tag
    - com.cloudbees.plugins.credentials.CredentialsProvider.Delete
    - hudson.model.View.Delete
    - hudson.model.Computer.Disconnect
    - hudson.model.Computer.Configure
    - hudson.model.Item.Workspace
    - hudson.model.Item.Configure
    - hudson.model.View.Create
    - hudson.model.Run.Delete
    - hudson.model.View.Read
    - hudson.model.Hudson.UploadPlugins
    - hudson.model.Computer.Connect
    - hudson.model.Item.Discover
    - com.cloudbees.plugins.credentials.CredentialsProvider.View
    - com.cloudbees.plugins.credentials.CredentialsProvider.Create
    - hudson.model.Hudson.Read
    - hudson.model.Item.Delete
    - hudson.model.View.Configure
    - hudson.model.Hudson.ConfigureUpdateCenter
    - com.cloudbees.plugins.credentials.CredentialsProvider.ManageDomains
    - hudson.model.Item.Read
    - hudson.model.Hudson.Administer
    - hudson.model.Hudson.RunScripts
    - hudson.model.Computer.Delete
    - hudson.model.Computer.Create
    - hudson.model.Item.Create
    - hudson.model.Item.Build
    - hudson.model.Computer.Build
    - hudson.model.Item.Cancel
    - com.cloudbees.plugins.credentials.CredentialsProvider.Update
    - hudson.model.Run.Update
  github_orgs:
    - hudson.model.View.Create
    - hudson.model.View.Read
    - hudson.model.View.Delete
    - hudson.model.Item.Read
    - hudson.model.Item.Discover
    - hudson.model.Item.Build
    - hudson.model.Item.Create
    - hudson.model.Hudson.Read
    - hudson.model.Item.Cancel
    - hudson.model.Item.Configure
    - hudson.model.Item.Delete
    - hudson.model.Item.Workspace
    - hudson.model.View.Configure

roles:
  admins:
    - admin
  github_orgs:
    - my-github-org

password_store_version: "1.6.5"
